### ISSUE TITLE
Some json body examples have an extra ',' at the end of the content

### ISSUE THREAD

**Issue by mcapodacqua** [TiendaNube/api-docs#15]
For example at the first [POST example of scripts doc](https://github.com/TiendaNube/api-docs/blob/master/resources/script.md#post-scripts).

As soon as I get time I will review all of the examples in order to submit a pull request

**Comment by jabuchae** [comment]
Thanks Maxi! I've committed some fixes but if you find more it'd be great to have your pull request :)

Here's the commit info in case you want to check it out: 
https://github.com/TiendaNube/api-docs/commit/d4b7bfdcf93139daebb0825d0e225d285547ba53

Feel free to reopen the issue if you think the commit wasn't enough.

Thanks a lot,
José

**Comment by mcapodacqua** [comment]
I can't reopen this issue again, but I submitted an pull request fixing some issues #16

**Comment by fonse** [comment]
Thanks! I merged the pull request. =)
