### ISSUE TITLE
Category resource does not return subcategories

### ISSUE THREAD

**Issue by ckozus** [TiendaNube/api-docs#24]
Hi there,

I'm getting the category tree for a store and the subcategories information seems to be missing.

The current category tree looks like this:

![screen shot 2016-08-30 at 8 20 00 am](https://cloud.githubusercontent.com/assets/12102/18087252/9600a510-6e8a-11e6-8e06-f1bcfc4374a9.png)

To get all the categories I use this request:

curl -H 'Authentication: bearer xxxxxxxxxx https://api.tiendanube.com/v1/180262/categories

and get the following json:

`	[
    {
        "id": 1540191,
        "name": {
            "es": "Encendido"
        },
        "description": {
            "es": ""
        },
        "handle": {
            "es": "encendido"
        },
        "parent": 0,
        "subcategories": [
            null
        ],
        "seo_title": {
            "es": null
        },
        "seo_description": {
            "es": null
        },
        "created_at": "2016-08-29T14:19:31+00:00",
        "updated_at": "2016-08-29T14:36:18+00:00"
    },
    {
        "id": 1540197,
        "name": {
            "es": "Baterias"
        },
        "description": {
            "es": ""
        },
        "handle": {
            "es": "baterias"
        },
        "parent": 1540191,
        "subcategories": [],
        "seo_title": {
            "es": null
        },
        "seo_description": {
            "es": null
        },
        "created_at": "2016-08-29T14:20:49+00:00",
        "updated_at": "2016-08-29T14:36:18+00:00"
    },
    {
        "id": 1540192,
        "name": {
            "es": "Filtros"
        },
        "description": {
            "es": ""
        },
        "handle": {
            "es": "filtros"
        },
        "parent": 0,
        "subcategories": [
            null,
            null,
            null,
            null
        ],
        "seo_title": {
            "es": null
        },
        "seo_description": {
            "es": null
        },
        "created_at": "2016-08-29T14:19:31+00:00",
        "updated_at": "2016-08-29T14:36:18+00:00"
    },
    {
        "id": 1540198,
        "name": {
            "es": "De Aire"
        },
        "description": {
            "es": ""
        },
        "handle": {
            "es": "de-aire"
        },
        "parent": 1540192,
        "subcategories": [],
        "seo_title": {
            "es": null
        },
        "seo_description": {
            "es": null
        },
        "created_at": "2016-08-29T14:20:49+00:00",
        "updated_at": "2016-08-29T14:36:18+00:00"
    },
    {
        "id": 1540199,
        "name": {
            "es": "De Aceite"
        },
        "description": {
            "es": ""
        },
        "handle": {
            "es": "de-aceite"
        },
        "parent": 1540192,
        "subcategories": [],
        "seo_title": {
            "es": null
        },
        "seo_description": {
            "es": null
        },
        "created_at": "2016-08-29T14:20:49+00:00",
        "updated_at": "2016-08-29T14:36:18+00:00"
    },
    {
        "id": 1540200,
        "name": {
            "es": "De Habitaculo"
        },
        "description": {
            "es": ""
        },
        "handle": {
            "es": "de-habitaculo"
        },
        "parent": 1540192,
        "subcategories": [],
        "seo_title": {
            "es": null
        },
        "seo_description": {
            "es": null
        },
        "created_at": "2016-08-29T14:20:49+00:00",
        "updated_at": "2016-08-29T14:36:18+00:00"
    },
    {
        "id": 1540201,
        "name": {
            "es": "De Nafta"
        },
        "description": {
            "es": ""
        },
        "handle": {
            "es": "de-nafta"
        },
        "parent": 1540192,
        "subcategories": [],
        "seo_title": {
            "es": null
        },
        "seo_description": {
            "es": null
        },
        "created_at": "2016-08-29T14:20:49+00:00",
        "updated_at": "2016-08-29T14:36:18+00:00"
    },
    {
        "id": 1540193,
        "name": {
            "es": "Frenos"
        },
        "description": {
            "es": ""
        },
        "handle": {
            "es": "frenos"
        },
        "parent": 0,
        "subcategories": [
            null
        ],
        "seo_title": {
            "es": null
        },
        "seo_description": {
            "es": null
        },
        "created_at": "2016-08-29T14:19:31+00:00",
        "updated_at": "2016-08-29T14:36:18+00:00"
    },
    {
        "id": 1540202,
        "name": {
            "es": "Pastillas de Freno"
        },
        "description": {
            "es": ""
        },
        "handle": {
            "es": "pastillas-de-freno"
        },
        "parent": 1540193,
        "subcategories": [],
        "seo_title": {
            "es": null
        },
        "seo_description": {
            "es": null
        },
        "created_at": "2016-08-29T14:22:30+00:00",
        "updated_at": "2016-08-29T14:36:18+00:00"
    },
    {
        "id": 1540194,
        "name": {
            "es": "Motor"
        },
        "description": {
            "es": ""
        },
        "handle": {
            "es": "motor"
        },
        "parent": 0,
        "subcategories": [
            null,
            null
        ],
        "seo_title": {
            "es": null
        },
        "seo_description": {
            "es": null
        },
        "created_at": "2016-08-29T14:19:31+00:00",
        "updated_at": "2016-08-29T14:36:18+00:00"
    },
    {
        "id": 1540203,
        "name": {
            "es": "Aditivos y Lubricantes"
        },
        "description": {
            "es": ""
        },
        "handle": {
            "es": "aditivos-y-lubricantes"
        },
        "parent": 1540194,
        "subcategories": [
            null,
            null
        ],
        "seo_title": {
            "es": null
        },
        "seo_description": {
            "es": null
        },
        "created_at": "2016-08-29T14:22:30+00:00",
        "updated_at": "2016-08-29T14:36:18+00:00"
    },
    {
        "id": 1540204,
        "name": {
            "es": "Aceite de Motor"
        },
        "description": {
            "es": ""
        },
        "handle": {
            "es": "aceite-de-motor"
        },
        "parent": 1540203,
        "subcategories": [],
        "seo_title": {
            "es": null
        },
        "seo_description": {
            "es": null
        },
        "created_at": "2016-08-29T14:22:30+00:00",
        "updated_at": "2016-08-29T14:36:18+00:00"
    },
    {
        "id": 1540205,
        "name": {
            "es": "Liquido Refrigerante"
        },
        "description": {
            "es": ""
        },
        "handle": {
            "es": "liquido-refrigerante"
        },
        "parent": 1540203,
        "subcategories": [],
        "seo_title": {
            "es": null
        },
        "seo_description": {
            "es": null
        },
        "created_at": "2016-08-29T14:22:30+00:00",
        "updated_at": "2016-08-29T14:36:18+00:00"
    },
    {
        "id": 1540206,
        "name": {
            "es": "Bombas"
        },
        "description": {
            "es": ""
        },
        "handle": {
            "es": "bombas"
        },
        "parent": 1540194,
        "subcategories": [
            null,
            null,
            null
        ],
        "seo_title": {
            "es": null
        },
        "seo_description": {
            "es": null
        },
        "created_at": "2016-08-29T14:22:30+00:00",
        "updated_at": "2016-08-29T14:36:18+00:00"
    },
    {
        "id": 1540241,
        "name": {
            "es": "De Aceite"
        },
        "description": {
            "es": ""
        },
        "handle": {
            "es": "de-aceite1"
        },
        "parent": 1540206,
        "subcategories": [],
        "seo_title": {
            "es": null
        },
        "seo_description": {
            "es": null
        },
        "created_at": "2016-08-29T14:36:17+00:00",
        "updated_at": "2016-08-29T14:36:18+00:00"
    },
    {
        "id": 1540242,
        "name": {
            "es": "De Agua"
        },
        "description": {
            "es": ""
        },
        "handle": {
            "es": "de-agua"
        },
        "parent": 1540206,
        "subcategories": [],
        "seo_title": {
            "es": null
        },
        "seo_description": {
            "es": null
        },
        "created_at": "2016-08-29T14:36:17+00:00",
        "updated_at": "2016-08-29T14:36:18+00:00"
    },
    {
        "id": 1540243,
        "name": {
            "es": "De Nafta"
        },
        "description": {
            "es": ""
        },
        "handle": {
            "es": "de-nafta1"
        },
        "parent": 1540206,
        "subcategories": [],
        "seo_title": {
            "es": null
        },
        "seo_description": {
            "es": null
        },
        "created_at": "2016-08-29T14:36:17+00:00",
        "updated_at": "2016-08-29T14:36:18+00:00"
    },
    {
        "id": 1540195,
        "name": {
            "es": "Suspensi\u00f3n y Direcci\u00f3n"
        },
        "description": {
            "es": ""
        },
        "handle": {
            "es": "suspension-y-direccion"
        },
        "parent": 0,
        "subcategories": [],
        "seo_title": {
            "es": null
        },
        "seo_description": {
            "es": null
        },
        "created_at": "2016-08-29T14:20:01+00:00",
        "updated_at": "2016-08-29T14:36:18+00:00"
    },
    {
        "id": 1540196,
        "name": {
            "es": "Transmisi\u00f3n"
        },
        "description": {
            "es": ""
        },
        "handle": {
            "es": "transmision"
        },
        "parent": 0,
        "subcategories": [],
        "seo_title": {
            "es": null
        },
        "seo_description": {
            "es": null
        },
        "created_at": "2016-08-29T14:20:01+00:00",
        "updated_at": "2016-08-29T14:36:18+00:00"
    }`

If you rake a look, all the subcategories fields are not correctly filled. Some of the, have an array of null elements where it should have the ids of the children categories.

I hope this helps.

Best,
Carlos.

**Comment by fonse** [comment]
It should be fixed now, thanks for reporting this!
