### ISSUE TITLE
error 500 accessing API

### ISSUE THREAD

**Issue by neuquino** [TiendaNube/api-docs#25]
I'm trying to test your API. 

I created a user, a partner (both with the same emails) and an app. My user doesn't have any products or orders.

I authenticated to my app using the OAuth flow and got an access token.

I tried to access /orders and /products and in both cases I got HTTP CODE 500 errors. 

I don't know if the error is caused because my user is new or because I registered both users (final user and partner user) using the same email. Despite that, it should not return a 500 code.

**Comment by fonse** [comment]
Disculpá por la demora! No había visto este issue hasta recién!

Te sigue pasando esto? De ser así, te puedo pedir por favor que mandes los detalles del request a api@tiendanube.com? La url exacta, con los headers y parámetros.

Gracias!

**Comment by neuquino** [comment]
Recién volví a probarlo y ahora me anduvo. 

Disculpá la molestia.

Saludos!
