### ISSUE TITLE
Orden de las ventas

### ISSUE THREAD

**Issue by neuquino** [TiendaNube/api-docs#27]
¿En el [GET /orders](https://github.com/tiendanube/api-docs/blob/master/resources/order.md#get-orders-1), existe alguna forma de especificar el orden de los resultados? En caso de que no se pueda, ¿Están ordenadas por algún criterio? ¿Cuál?

Gracias!

**Comment by fonse** [comment]
Eso ya no te sabría contastar. Las dudas de la API te sugiero que las mandes a api@tiendanube.com, ahí te van a poder responder mejor.

Saludos y disculpá que no te pude resolver la duda.
