### ISSUE TITLE
Webhooks don't work.

### ISSUE THREAD

**Issue by trinhminhtriet** [TiendaNube/api-docs#31]
We're developing an application on Tiendanube.

We have added 3 webhooks into Tiendanube via API.
But after the events were called, our callback URL was NOT called.

Here are the webhooks what are created in Tiendanube:
 stdClass Object
(
    [id] => 48848
    [event] => order/created
    [url] => http://nuvemshop-bibliomundi.demo.devinition.com/tiendanube/1/callback/order/created
    [created_at] => 2017-03-23T08:30:04+0000
    [updated_at] => 2017-03-23T10:10:58+0000
)
 stdClass Object
(
    [id] => 48852
    [event] => product/created
    [url] => http://nuvemshop-bibliomundi.demo.devinition.com/tiendanube/1/callback/product/created
    [created_at] => 2017-03-23T10:56:35+0000
    [updated_at] => 2017-03-23T10:56:35+0000
)
 stdClass Object
(
    [id] => 48854
    [event] => product/deleted
    [url] => http://nuvemshop-bibliomundi.demo.devinition.com/tiendanube/1/callback/product/deleted
    [created_at] => 2017-03-23T11:04:48+0000
    [updated_at] => 2017-03-23T11:04:48+0000
)

Are there any advice?

**Comment by PatagoniaTec** [comment]
not working for me eather

**Comment by lombo** [comment]
Hey guys, we will be checking this out and giving an update. Thx for the heads up!

**Comment by lombo** [comment]
Webhooks should now be fixed. Please open another issue if it happens again.
