### ISSUE TITLE
Mejorar la actualización de variantes de producto

### ISSUE THREAD

**Issue by caesaram** [TiendaNube/api-docs#40]
Buenas tardes. 
**Actualmente poseen una limitación de transacciones vía API de 500 cada 5 minutos.**

La actualización de variantes mediante API, se realiza una a una enviando un PUT por cada variant (indefectiblemente). 
Si un producto posee muchas variantes, al tener que actualizarlas de a una, el límite de 500 operaciones es bajísimo, sobre todo si se sincroniza, por ejemplo, el stock en días de eventos comerciales constantemente (día de la madre, navidad, hot sales, etc).

**Les propongo que continúe el límite en 500 operaciones cada 5 minutos, pero que permitan actualizar las variantes de un producto, realizando una única operación PUT de la entidad "products", cargando el array de variantes a modificar en el atributo "variants" (array), del objeto "products".**

De esta manera, estaríamos enviando en un único PUT, el update de las "n" variantes que tenga ese producto, utilizando solamente una transacción. Beneficia tanto a ustedes (ya que no hace falta que modifiquen el límite de requests), como al cliente (ya que no le quedan variantes desfasadas por límite de requests).

Actualmente nos manejamos armando una queue de transacciones y con el reset-time, no obstante, 5 minutos para un día comercial de ventas es demasiado tiempo.

Saludos cordiales.

**Comment by contabilium** [comment]
Sumo mi comentario pero desde mi perspectiva 500 operaciones cada 5 minutos es muy poco.
Imagenes el escenario en donde una Tienda tiene 1000 productos con 3 variantes cada uno.
El dolar sube y el desea actualizar los precios todos juntos... :)

**Comment by devsdmf** [comment]
Hi @caesaram and @contabilium, thank you for the feedback about this limitation.

We're working to improve our API through new versions, we're considering this feedback for the next release.

I'll keep this issue open so I can notify both you about any update of this issue, ok? Hope in some weeks we will have a fix for this problem.

Best regards.

**Comment by caesaram** [comment]
@devsdmf Thanks for your reply

**Comment by devsdmf** [comment]
Hi @caesaram and @contabilium, first of all I wanna say sorry about the delay to follow up with you about this problem.

A week ago we updated the API with a new rate limit system, which now uses a Leaky Bucket based throttling strategy. Now you can perform up to 2 requests per second, with bursts of 40 requests, without get a 429 error.

I hope that this would help both you in these problems and I want to say that we're continuously improving our API in order to give a better experience to the developers that are integrating their applications/platforms with us.

Best regards!

**Comment by caesaram** [comment]
Hi @devsdmf , thanks for the improvement and for notice us! We 'll be modifying the logic according the new specs. 

Best regards.

César
