### ISSUE TITLE
"error":"invalid_grant" following the example of authentication

### ISSUE THREAD

**Issue by jsuarez** [TiendaNube/api-docs#51]
When i try to autenticate following the example:

curl https://www.tiendanube.com/apps/authorize/token --data 'client_id=123&client_secret=abcdef&grant_type=authorization_code&code=xyz'

i'm using my own app info:

curl https://www.tiendanube.com/apps/authorize/token --data 'client_id=737&client_secret=vtA83WeAmda8ltczosGBrSjM438EuQTEdMDCCsWiQVsyhkNu&grant_type=authorization_code&code=35fd3e9317ad8082d71a935a0e9574f1e4213181'

and every time (with different codes of different stores) i get:
{"error":"invalid_grant","error_description":"The authorization code has expired"}

**Comment by devsdmf** [comment]
Hi @jsuarez.

Please, e-mail us with your problem at api@tiendanube.com so we can try to figure out what is going on.

Also, I'm deactivating this issue because you're providing sensitive information in the description.
